### ISSUE TITLE
Org mode fontification error in #<buffer ...

### ISSUE THREAD

**Issue by MicLennartz** [vincentbernat/junos-mode#2]
Hi,

I'm not an emacs expert, but using the junos-mode quite intense, especially because of it's babel integration.

Everything works quite nicely, but I can't get the syntax fontification working in org-mode.
(Code blocks in other languages are working well)

Do you have a hint, how to fix this ?

emacs-26.1 on Mac (+contrib package)

/Michael

**Comment by vincentbernat** [comment]
I am not using Emacs 26.1 yet, so the problem may be around that. Which version of org-mode are you using? Does fontification works outside org-mode?

**Comment by MicLennartz** [comment]
My system is running on "Org mode version 9.1.11" from ELPA. But there are no specific reasons for that version.

And yes, the fontification of junos-mode is working well outside org-mode.

But I have to admit, that I added a few additional keyword matches to 'junos-mode.el' to improve the syntax highlighting in JunOS "set" notation. After some further investigations today it came out, that some of these additions seem to break fontification in org-mode.

**Comment by vincentbernat** [comment]
Post your additions here, maybe I can help.

**Comment by MicLennartz** [comment]
This is the 'diff'. To that extend it's working well in junos-mode, even inside an org code block.
But the patterns for 'numbers' and 'Jinja2 fields' I had comment out. They are not working under org-mode and break the complete fontification there.

(Would be great, if you would add this to your official branch.) ;-)

`diff --git a/junos-mode.el b/junos-mode.el
index add5bc3..68e6c8e 100644
--- a/junos-mode.el
+++ b/junos-mode.el
@@ -53,6 +53,22 @@
     ("^\\s-*\\(\\(inactive\\|active\\|delete\\|replace\\|protect\\|unprotect\\):\\s-+\\)?\\(\\sw+\\)"
      (1 'font-lock-keyword-face nil t)
      (3 'font-lock-type-face))
+    ;; Jinja2 fields
+    ;;("{{[^{}]*}}" . 'button)
+    ;; numbers
+    ;;("\\b[0-9-]*\\b" . 'font-lock-constant-face)
+    ;; Major sections of the configuration
+    ("\\b\\(system\\|forwarding-options\\|routing-options\\|routing-instances\\|logical-systems\\|vlans\\|bridge-domains\\|dynamic-profiles\\|interfaces\\|snmp\\|poe\\|ethernet-switching-options\\|security\\|groups\\|policy-options\\|protocols\\|chassis\\|firewall\\|applications\\|multi-chassis\\|redundant-power-system\\|version\\|services\\|virtual-chassis\\|event-options\\|class-of-service\\|access\\|accounting-options\\|diameter\\|fabric\\|multicast-snooping-options\\|switch-options\\|wlan\\|smtp\\|schedulers\\)\\b" . 'font-lock-keyword-face)
+    ;; policy reject actions
+    ("\\(deny\\|discard\\|reject\\)" . 'custom-invalid)
+    ;; policy allow actions
+    ("\\(accept\\|permit\\)" . 'custom-state)
+    ;; interface names
+    ("\\b\\(\\(ge\\|et\\|so\\|fe\\|gr\\|xe\\|lt\\|vt\\si\\|sp\\)-[0-9]+/[0-9]+/[0-9]+\\)\\b\\|\\b\\(st\\|lo\\|me\\|vme\\|ae\\)[0-9]\\{1,3\\}\\b" . 'font-lock-variable-name-face)
+    ;; descriptions, even without quotes
+    ("\\bdescription\s\\([a-zA-Z0-9/<>:_-]+\\)" 1 'font-lock-string-face)
+    ;; user specified arbitrary names
+    ("\s\\(logical-systems\\|dynamic-profiles\\|jsrc-partition\\|partition\\|filter input\\|filter output\\|access-profile\\|dscp\\|dscp-ipv6\\|exp\\|ieee-802\.1\\|ieee-802\.1ad\\|inet-precedence\\|scheduler-map\\|scheduler-maps\\|input-traffic-control-profile-remaining\\|input-traffic-control-profile\\|traffic-control-profiles\\|output-traffic-control-profile-remaining\\|output-traffic-control-profile\\|output-forwarding-class-map\\|scheduler-map-chassis\\|fragmentation-maps\\|source-prefix-list\\|bridge-domains\\|group\\|mime-pattern\\|url-pattern\\|label-switched-path\\|admin-groups\\|custom-url-category\\|profile\\|url-whitelist\\|url-blacklist\\|ca-profile\\|idp-policy\\|active-policy\\|interface-set\\|interface-range\\|count\\|destination-prefix-list\\|schedulers\\|drop-profiles\\|forwarding-class\\|forwarding-class-map\\|import\\|export\\|instance\\|utm-policy\\|ids-option\\|next-hop-group\\|routing-instances\\|rule\\|rule-set\\|pool\\|class\\|unit\\|port-mirror-instance\\|from-zone\\|to-zone\\|apply-groups\\|file\\|host-name\\|domain-name\\|path\\|domain-search\\|community delete\\|community add\\|community set\\|community\\|trap-group\\|policy\\|policy-statement\\|import-policy\\|instance-export\\|instance-import\\|vrf-import\\|vrf-export\\|import\\|export\\|keep-import\\|inter-area-prefix-import\\|inter-area-prefix-export\\|network-summary-export\\|network-summary-import\\|egress-policy\\|bootstrap-import\\|bootstrap-export\\|filter\\|prefix-list\\|proposal\\|address-set\\|scheduler\\|rib-groups\\|groups\\|security-zone\\|term\\|application\\|application-set\\|vlans\\|gateway\\|user\\|policer\\|lsp\\|condition\\)\s\\([a-zA-Z0-9_-]+\\)" 2 'info-header-node)
     ;; IP
     ("\\([[:digit:]]+\\.\\)\\{3\\}[[:digit:]]+\\(/[[:digit:]]+\\)?" . 'font-lock-constant-face)
     ("\\(?:\\(?:[[:xdigit:]]+\\)?:\\)+[[:xdigit:]]*\\(/[[:digit:]]+\\)?" . 'font-lock-constant-face))`
