### ISSUE TITLE
alterate config mode possible ?

### ISSUE THREAD

**Issue by MicLennartz** [vincentbernat/junos-mode#3]
Hi,

I'm using your module quite frequently, which is very convenient.
But from time to time there's a need to do some configurations in 'private' mode, which is not yet supported in your module.

I've attempted (with my basic knowledge on PyEz) to hardcode the mode in junos.py file, but this doesn't seem to be working. No error is raised, but diffs are not shown and no config change is committed on the device. I suspect, that this related to your specific session handling somehow.

Do you know, how this could be achieved ?
(preferably with an additional 'mode' parameter in the emacs ob part?)

//Michael

**Comment by vincentbernat** [comment]
What change did you try?

**Comment by MicLennartz** [comment]
I've tried something like this ...
`diff --git a/junos.py b/junos.py
index ec5b7fb..903c91f 100755
--- a/junos.py
+++ b/junos.py
@@ -219,7 +219,7 @@ def do_load(tag, args, lines):
     if len(args) != 1:
         raise TypeError("load expects a unique argument")
     with device(args[0]) as dev:
-        with Config(dev) as cu:
+        with Config(dev, mode='private') as cu:
             try:
                 cu.load("\n".join(lines))
             except ConfigLoadError as ce:
@@ -237,7 +237,7 @@ def do_diff(tag, args, lines):
     if len(args) != 1:
         raise TypeError("diff expects a unique argument")
     with device(args[0]) as dev:
-        with Config(dev) as cu:
+        with Config(dev, mode='private') as cu:
             diff = cu.diff()
             output(tag, ["ok", (diff and diff.strip()) or ""])

@@ -248,7 +248,7 @@ def do_check(tag, args, lines):
     if len(args) != 1:
         raise TypeError("check expects a unique argument")
     with device(args[0]) as dev:
-        with Config(dev) as cu:
+        with Config(dev, mode='private') as cu:
             try:
                 cu.commit_check()
             except CommitError as ce:
@@ -269,7 +269,7 @@ def do_rollback(tag, args, lines):
     if len(args) == 2:
         rid = int(args[1])
     with device(args[0]) as dev:
-        with Config(dev) as cu:
+        with Config(dev, mode='private') as cu:
             cu.rollback(rid)
             output(tag, "ok")

@@ -280,7 +280,7 @@ def do_commit(tag, args, lines):
     if len(args) not in (1, 2):
         raise TypeError("commit expects one or two arguments")
     with device(args[0]) as dev:
-        with Config(dev) as cu:
+        with Config(dev, mode='private') as cu:
             try:
                 if len(args) == 2:
                     cu.commit(confirm=int(args[1]))`

**Comment by vincentbernat** [comment]
I suppose `Config(dev, mode='private')` creates a separate private session each time. We would need to store the configuration session with the device. However, I am not sure how to prevent configuration session to lie around if we make this change.

**Comment by MicLennartz** [comment]
I've to admit, that I don't understand, why the current approach is working. 😉
For my eyes it seem to create new config sessions for each step individually (load, diff,check,commit).

**Comment by vincentbernat** [comment]
Yes, but since it is not using the private mode, the configuration persists across the sessions. Having a global config session (or one private, one non-private) would solve your issue but it also means you'll always have an open config session, even when you don't need it anymore, notably it will warn you "somebody else is also in edit mode" until you close Emacs.

**Comment by MicLennartz** [comment]
This sounds like this is not worth the efforts then:
A global config session seems to be the only way, and keeping all sessions open is not an option. So we would have to deal with session timeouts and auto-close functions ... too much for me.
